apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: simple-dependent-stack
  title: Simple Dependent Tech Stack
  description: Choose domain, then tech stacks filter based on that
  tags:
    - generator
    - frontend
    - backend
    - database

spec:
  owner: user:your-username
  type: service

  parameters:
    - title: Project Stack Selection
      required:
        - domain
      properties:
        domain:
          title: Select a Domain
          type: string
          enum:
            - Banking
            - Insurance
            - HealthCare
            - Education

      dependencies:
        domain:
          oneOf:
            - properties:
                domain:
                  const: Banking
                frontend:
                  title: UI Framework
                  type: string
                  enum: [Vue.js, Next.js, Typescript]
                backend:
                  title: Backend Platform
                  type: string
                  enum: [Java, Python, Ruby]
                database:
                  title: Database
                  type: string
                  enum: [MYSQL, PostgreSQL]
              required:
                - frontend
                - backend
                - database

            - properties:
                domain:
                  const: Insurance
                frontend:
                  title: UI Framework
                  type: string
                  enum: [React, Angular]
                backend:
                  title: Backend Platform
                  type: string
                  enum: [Scala, Go, Django]
                database:
                  title: Database
                  type: string
                  enum: [MYSQL, PostgreSQL]
              required:
                - frontend
                - backend
                - database

            - properties:
                domain:
                  const: HealthCare
                frontend:
                  title: UI Framework
                  type: string
                  enum: [Three.js, ReactJs, Angular 2+]
                backend:
                  title: Backend Platform
                  type: string
                  enum: [Springboot, ASP.NET]
                database:
                  title: Database
                  type: string
                  enum: [MYSQL, PostgreSQL]
              required:
                - frontend
                - backend
                - database

            - properties:
                domain:
                  const: Education
                frontend:
                  title: UI Framework
                  type: string
                  enum: [Vue.js, Next.js, Typescript, Three.js, ReactJs, Angular 2+]
                backend:
                  title: Backend Platform
                  type: string
                  enum:
                    - Java
                    - Python
                    - Ruby
                    - PHP Kotlin
                    - C sharp
                    - Perl
                    - Scala
                    - Go
                    - Djangi
                    - Springboot
                    - ASP.NET
                database:
                  title: Database
                  type: string
                  enum: [MYSQL, PostgreSQL]
              required:
                - frontend
                - backend
                - database

    - title: Repository Info
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
              - github.kyndryl.net

  steps:
    - id: fetch
      name: Fetch Skeleton
      action: fetch:template
      input:
        url: ./skeleton
        values:
          domain: ${{ parameters.domain }}
          frontend: ${{ parameters.frontend }}
          backend: ${{ parameters.backend }}
          database: ${{ parameters.database }}
          repoUrl: ${{ parameters.repoUrl }}

    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        repoUrl: ${{ parameters.repoUrl }}
        description: Generated project for ${{ parameters.domain }} domain using ${{ parameters.frontend }} frontend, ${{ parameters.backend }} backend, and ${{ parameters.database }} database.

    - id: register
      name: Register in Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml

  output:
    links:
      - title: 🔗 Open GitHub Repository
        icon: github
        url: ${{ steps.publish.output.remoteUrl }}

      - title: 💻 Open in VSCode
        icon: code
        url: https://vscode.dev/github/${{ parameters.repoUrl | parseRepoUrl | pick('owner') }}/${{ parameters.repoUrl | parseRepoUrl | pick('repo') }}

      - title: 🚀 Open in Replit
        icon: rocket
        url: https://replit.com/github/${{ parameters.repoUrl | parseRepoUrl | pick('owner') }}/${{ parameters.repoUrl | parseRepoUrl | pick('repo') }}

      - title: 📘 Open in Catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
